local h = require('tests.helpers')

describe('move()', function()
  before_each(function()
    h.reset_backend()
  end)

  it('moves right to adjacent pane', function()
    local backend = require('smart-splits-backend-template')
    local mock_mux = require('smart-splits-backend-template.mock_mux')
    assert.are.equal(0, mock_mux.get_state().current_pane_id)
    assert.is_true(backend.move('right'))
    assert.are.equal(1, mock_mux.get_state().current_pane_id)
  end)

  it('moves left to adjacent pane', function()
    local backend = require('smart-splits-backend-template')
    local mock_mux = require('smart-splits-backend-template.mock_mux')
    backend.move('right')
    assert.is_true(backend.move('left'))
    assert.are.equal(0, mock_mux.get_state().current_pane_id)
  end)

  it('moves down to adjacent pane', function()
    local backend = require('smart-splits-backend-template')
    local mock_mux = require('smart-splits-backend-template.mock_mux')
    assert.is_true(backend.move('down'))
    assert.are.equal(2, mock_mux.get_state().current_pane_id)
  end)

  it('moves up to adjacent pane', function()
    local backend = require('smart-splits-backend-template')
    local mock_mux = require('smart-splits-backend-template.mock_mux')
    backend.move('down')
    assert.is_true(backend.move('up'))
    assert.are.equal(0, mock_mux.get_state().current_pane_id)
  end)

  it('returns false at edge with at_edge=stop', function()
    local backend = require('smart-splits-backend-template')
    assert.is_false(backend.move('left', { at_edge = 'stop' }))
  end)

  it('wraps at edge with at_edge=wrap', function()
    local backend = require('smart-splits-backend-template')
    local mock_mux = require('smart-splits-backend-template.mock_mux')
    assert.is_true(backend.move('left', { at_edge = 'wrap' }))
    assert.are.equal(1, mock_mux.get_state().current_pane_id)
  end)

  it('splits at edge with at_edge=split', function()
    local backend = require('smart-splits-backend-template')
    local mock_mux = require('smart-splits-backend-template.mock_mux')
    local initial_count = #mock_mux.get_state().panes
    assert.is_true(backend.move('left', { at_edge = 'split' }))
    assert.are.equal(initial_count + 1, #mock_mux.get_state().panes)
  end)

  it('returns false when backend is disabled', function()
    local backend = require('smart-splits-backend-template')
    h.disable_backend()
    assert.is_false(backend.move('right'))
  end)
end)
