local capture = require('tests.fixtures.capture_user_vars')
local h = require('tests.helpers')

describe('resize()', function()
  before_each(function()
    h.reset_backend()
  end)

  it('writes a SMART_SPLITS_REQ resize request', function()
    local backend = require('smart-splits-backend-wezterm')
    assert.is_true(backend.resize('right', { amount = 5 }))

    local name, value = capture.decode_last()
    assert.are.equal('SMART_SPLITS_REQ', name)
    local payload = vim.json.decode(value)
    assert.are.equal('resize', payload.action)
    assert.are.equal('right', payload.dir)
    assert.are.equal(5, payload.amount)
  end)

  it('defaults amount to 1 when not specified', function()
    local backend = require('smart-splits-backend-wezterm')
    backend.resize('left')
    local _, value = capture.decode_last()
    assert.are.equal(1, vim.json.decode(value).amount)
  end)

  it('floors a fractional amount', function()
    local backend = require('smart-splits-backend-wezterm')
    backend.resize('down', { amount = 3.7 })
    local _, value = capture.decode_last()
    assert.are.equal(3, vim.json.decode(value).amount)
  end)
end)
